// Requires a running local prototype and Playwright with a usable Chromium browser.
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
(async()=>{
 const browser=await chromium.launch({headless:true, ...(process.env.CHROME_PATH ? {executablePath:process.env.CHROME_PATH} : {})});
 const page=await browser.newPage({viewport:{width:1440,height:1000}, reducedMotion:'reduce'});
 const errors=[]; page.on('pageerror', e=>errors.push(e.message));
 await page.goto(process.env.PROTOTYPE_URL || 'http://127.0.0.1:8765');
 await page.getByText('Local · No paid APIs',{exact:true}).waitFor();
 await page.screenshot({path:'/private/tmp/launch-intake.png'});
 await page.getByRole('button',{name:'Voice notes → actions'}).click();
 await page.getByRole('button',{name:'Shape the brief'}).click();
 await page.getByLabel('Problem it solves').fill('Spoken ideas and commitments disappear before I act on them.');
 await page.getByLabel('Core benefit',{exact:true}).fill('Turn spoken ideas into searchable notes and actionable next steps.');
 await page.getByLabel('Work offline').uncheck();
 await page.getByRole('button',{name:'Confirm brief & inspect sources'}).click();
 await page.getByRole('heading',{name:'Who feels the problem?'}).waitFor();
 await page.locator('#evidence-disclosure').getByText('Inspect sources and research gaps',{exact:true}).click();
 await page.locator('#evidence-before .source').first().waitFor();
 await page.getByRole('button',{name:'Confirm audiences & run assessment'}).click();
 await page.getByRole('heading',{name:'Your launch assessment.'}).waitFor();
 await page.screenshot({path:'/private/tmp/launch-report.png',fullPage:true});
 if (!await page.getByText('Insufficient evidence',{exact:true}).count()) throw new Error('Missing verdict');
 await page.getByRole('tab',{name:'Stress tests'}).click();
 await page.getByText(/0 LLM agents/).waitFor();
 await page.getByRole('tab',{name:'Compare',exact:true}).click();
 await page.getByLabel('Alternative core benefit').fill('Keep searchable voice notes entirely offline.');
 await page.getByRole('button',{name:'Compare with baseline'}).click();
 await page.getByText('No numerical delta: at least one run has missing inputs.').waitFor();
 await page.screenshot({path:'/private/tmp/launch-compare.png',fullPage:true});
 await page.getByRole('button',{name:/Save (run|comparison)/}).click();
 await page.getByRole('button',{name:'Saved locally',exact:true}).waitFor();
 const downloadPromise=page.waitForEvent('download'); await page.getByRole('button',{name:'Export JSON'}).click(); const download=await downloadPromise;
 await download.saveAs('/private/tmp/launch-browser-export.json');
 await page.getByRole('button',{name:'Start another assessment'}).click();
 await page.getByRole('heading',{name:'Saved assessments'}).waitFor();
 await page.locator('[data-run]').first().click();
 await page.getByRole('tab',{name:'Stress tests'}).click();
 await page.getByText(/Saved run from/).waitFor();
 await page.getByRole('button',{name:'Start another assessment'}).click();
 await page.getByLabel('Your consumer SaaS idea').fill('A habit coach that helps people restart a routine after a missed day with a small next action.');
 await page.getByRole('button',{name:'Shape the brief'}).click();
 await page.getByLabel('Problem it solves').fill('Missing a day causes people to abandon routines.');
 await page.getByLabel('Core benefit',{exact:true}).fill('Restart a routine with one smaller next action.');
 await page.getByRole('button',{name:'Confirm brief & inspect sources'}).click();
 await page.getByLabel('Need-based group 1').waitFor();
 if (!await page.getByLabel('Need-based group 1').inputValue().then(v=>v.includes('Choose'))) throw new Error('Second idea got voice audiences');
 await page.getByText('Add explicit quant inputs',{exact:false}).click();
 for(const input of await page.locator('#factor-fields input[type=number]').all()) await input.fill('0.5');
 for(const input of await page.locator('#factor-fields input:not([type=number])').all()) await input.fill('Explicit browser-test assumption, not evidence.');
 await page.getByRole('button',{name:'Confirm audiences & run assessment'}).click();
 await page.getByRole('heading',{name:'Your launch assessment.'}).waitFor();
 await page.getByText('0.500',{exact:true}).waitFor();
 await page.getByRole('tab',{name:'Compare',exact:true}).click();
 await page.getByLabel('Alternative core benefit').fill('Restart a missed routine without migrating an existing task list.');
 await page.getByLabel('Optional model factor to change').selectOption('switching_ease');
 await page.getByLabel('Assumed value, 0–1').fill('0.9');
 await page.getByLabel('Why this assumption?').fill('Assume avoiding migration reduces switching effort. Unvalidated.');
 await page.getByRole('button',{name:'Compare with baseline'}).click();
 await page.getByText(/Heuristic index change: \+0.040/).waitFor();
 const priceOption = await page.locator('#scenario-factor option[value=price_fit]').count();
 if(priceOption) throw new Error('Price comparison control is present');
 await page.getByRole('tab',{name:'Outlook',exact:true}).click();
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/private/tmp/launch-mobile.png',fullPage:true});
 const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 if(overflow) throw new Error('Mobile overflow');
 if(errors.length)throw new Error(errors.join('\n'));
 console.log(JSON.stringify({passed:true,flows:2,liveSources:true,savedReplay:true,quantDelta:0.04,priceDisabled:true,export:true,mobileOverflow:overflow,consoleErrors:errors}));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
